<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LangVersion>default</LangVersion>
	<Nullable>enable</Nullable>
    <TargetFrameworks>netstandard2.0;net8.0;net9.0</TargetFrameworks>
    <PackageId>AWSSSM.Provider</PackageId>
    <Title>AWSSSM.Provider</Title>
    <Description>An AWS SSM Parameter Store-backed configuration provider for .NET applications using Microsoft.Extensions.Configuration.</Description>
    <PackageTags>aws;ssm;parameterstore;configuration;provider;dotnet;extension</PackageTags>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.SimpleSystemsManagement" />
    <PackageReference Include="LayeredCraft.StructuredLogging" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\AWSSecretsManager.Provider\Internal\JsonFlattener.cs" Link="Internal\JsonFlattener.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="" Visible="false" />
    <None Include="..\..\icon.png" Pack="true" PackagePath="" Visible="false" />
  </ItemGroup>
</Project>
