name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - beta
      - release/*
    tags:
      - v*
permissions: write-all
jobs:
  build:
    uses: LayeredCraft/devops-templates/.github/workflows/package-build.yaml@feature/multi-framework-mtp-support
    with:
      dotnet-version: |
        8.0.x
        9.0.x
      hasTests: true
      useMtpRunner: true
      testDirectory: "tests"
    secrets: inherit