name: PR Build

on:
  pull_request:
    branches:
      - main
permissions: write-all
jobs:
  build:
    uses: LayeredCraft/devops-templates/.github/workflows/pr-build.yaml@feature/multi-framework-mtp-support
    with:
      solution: AWSSecretsManager.sln
      hasTests: true
      dotnetVersion: |
        8.0.x
        9.0.x
      runCdk: false
      useMtpRunner: true
      testDirectory: "tests"
    secrets: inherit