name: PR Build

on:
  pull_request:
    branches:
      - main
permissions: write-all
jobs:
  build:
    uses: LayeredCraft/devops-templates/.github/workflows/pr-build.yaml@coverage
    with:
      solution: AWSSecretsManager.sln
      hasTests: true
      dotnetVersion: |
        8.0.x
        9.0.x
      runCdk: false
      coverageThreshold: 80
    secrets: inherit